### ISSUE TITLE
Allennlp Support

### ISSUE THREAD

**Issue by edenlightning** [PyTorchLightning/lightning-bolts#128]
This was originally discussed in https://github.com/PyTorchLightning/pytorch-lightning/issues/987, and @mikerossgithub tried to add this to PL in https://github.com/PyTorchLightning/pytorch-lightning/pull/1993, but since this depends on allennlp, this issue was transferred to Bolts here. (just for the record)

**Comment by yucoian** [comment]
What happened?? What's going on ??
