### ISSUE TITLE
Incorrect model link for CPCV2-resnet18?

### ISSUE THREAD

**Issue by yaminibansal** [PyTorchLightning/lightning-bolts#181]
## 🐛 Bug

Following the docs https://pytorch-lightning-bolts.readthedocs.io/en/latest/self_supervised_models.html I was loading a pretrained ResNet-18 for CPCV2, but it seems that it returns a ResNet-101. Maybe the URL to the trained model is incorrect?

![Screen Shot 2020-09-04 at 9 09 09 PM](https://user-images.githubusercontent.com/8604826/92293618-efbf2800-eef2-11ea-9696-8f6292b202f7.png)

There also seems to be an unrelated bug when it loads the model in file https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/32fb560a429532dfb40a5935ca7674990dae1f66/pl_bolts/models/self_supervised/cpc/cpc_module.py 
Line 160 should be `elif encoder not in available_weights`?

**Comment by ovshake** [comment]
Hi, 
I am facing the same issue. Is there a fix?

**Comment by ananyahjha93** [comment]
The docs wrongly mention resnet-18, we have weights for resnet-101 mentioned in the docs for STL-10 and CIFAR10 at the moment. I'll update the docs to avoid this confusion.

**Comment by Borda** [comment]
@ananyahjha93 is this fixed or @yaminibansal mind send a fix PR?

**Comment by ananyahjha93** [comment]
We are deprecating the self-supervised learning paper implementations in bolts and instead provided a [VISSL](https://vissl.ai/) integration in PyTorch Lightning Flash which can be used to train models using self-supervised learning algorithms. You can refer to the documentation [here](https://lightning-flash.readthedocs.io/en/latest/reference/image_embedder.html).
