### ISSUE TITLE
Decouple DataModules from Models

### ISSUE THREAD

**Issue by nateraw** [PyTorchLightning/lightning-bolts#207]
## 🚀 Feature

Most of the models have 'datamodule' as an init arg and/or implement a 'default datamodule' and set that as a class attribute if datamodule is not passed on init.

This causes problems...
- it explicitly bakes in dataset specific stuff in the model (which kinda defeats the purpose of the datamodule)
- it forces the user to use a datamodule (not cool, dude!)

So, we need to go through each model and decouple the hard-coded datamodules to get rid of these issues.

**Comment by akihironitta** [comment]
We still have things to do here, so could you keep this issue open?

As far as I could find, we need to decouple datamodules from the following models:
- `pl_bolts.models.self_supervised.cpc.cpc_module.CPCV2`
- `pl_bolts.models.self_supervised.amdim.amdim_module.AMDIM`
