### ISSUE TITLE
Add detectron2 implementation

### ISSUE THREAD

**Issue by williamFalcon** [PyTorchLightning/lightning-bolts#21]
https://github.com/facebookresearch/detectron2

**Comment by justusschock** [comment]
This is a rather large repo. Maybe it would be best to also outsource this to a separate repo here? Especially since they also need to compile cpp stuff there. If we add this here, we probably also need to ship wheels for each torch version or always have compilation during install...

**Comment by edgarriba** [comment]
notice that parts of the detectron is now split under torchvision to make it more flexible. Maybe its worth directly wrapping the needed things from torchvision.

**Comment by Borda** [comment]
yeah, we shall port just some models at the beginning...

**Comment by hiyyg** [comment]
I think it would be nice if you can change provide some examples of using pl's trainer to train d2's builtin models by only changing the trainer.

**Comment by yash-overjet** [comment]
@williamFalcon any progress on this planned ?

**Comment by zhiqwang** [comment]
FYI, seems that detectron2 supports training with pytorch-lightning now https://github.com/facebookresearch/detectron2/blob/main/tools/lightning_train_net.py
