### ISSUE TITLE
Add basic NLP models like text-classification or sequence-to-sequence. 

### ISSUE THREAD

**Issue by PetrochukM** [PyTorchLightning/lightning-bolts#229]
## 🚀 Feature
Incorporate basic NLP models like text classification or sequence-to-sequence models.

Do I need to clarify further?

**Comment by Borda** [comment]
mind have look at #128 #34

**Comment by oke-aditya** [comment]
Yes, it would be great to extend support to NLP. We can probably add torchtext support as well.

torchtext is currently under revamp, the old data modules are getting deprecated and in October release we will have stable and good torchtext on which we can build pipelines.

Have a look [here](https://github.com/pytorch/text/releases).

**Comment by nateraw** [comment]
I've been working on this. I think we want options for using both `torchtext` and HuggingFace `transformers`. So much research has gone towards transformers in NLP, so I want to support that...but we should also support torchtext stuff too. 

I'm thinkin for torchtext, we use their data sources, for HuggingFace, we use their `datasets` library. That way we can install either version independently so the dependencies don't start stacking up. 

What do you think?
