### ISSUE TITLE
CPCV2 Implementation Clarification

### ISSUE THREAD

**Issue by rschwarz15** [PyTorchLightning/lightning-bolts#301]
#### What is your question?
Can I get a clarification on the implementation of CPCV2. 

In the paper they implement predictions in four directions as well as patch based augmentation. From what I can see from reading through the code, the predictions are in one direction and the augmentation is performed on the entire image prior to creating the grid of patches. 

Am I correct that both of these are slight deviations from the implementation of the paper?

**Comment by ananyahjha93** [comment]
@williamFalcon I think you might be able to answer this better.
