### ISSUE TITLE
A bug in precision_at_k function that causes the reported top_k accuracy to be down-scaled by batch size

### ISSUE THREAD

**Issue by ahmedhshahin** [PyTorchLightning/lightning-bolts#361]
## 🐛 A bug in precision_at_k function that causes the reported top_k accuracy to be down-scaled by batch size

The mentioned function divides the accuracy by batch_size in [this line](https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/70833f0bac73801a4c970a6ba9324b8469efede8/pl_bolts/metrics/aggregation.py#L32) (to calculate mean accuracy for this batch). However, it returns a list. This list we usually calculate the mean over it again in validation_epoch_end, as in [this line](https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/70833f0bac73801a4c970a6ba9324b8469efede8/pl_bolts/models/self_supervised/moco/moco2_module.py#L301), which means we divide by the batch size **two times**. Consequently, the reported accuracy is scaled down by the batch size.

A simple solution to this would be by returning the scalar mean accuracy, not a list.

### To Reproduce

1. Go to pl_bolts.models.self_supervised
2. Run MocoV2
3. Monitor val_acc5 or val_acc1

### Expected behavior
Returning the correct accuracy values. What happens with the current implementation is that it returns accuracy/batch_size.

### Environment

 - PyTorch Version (e.g., 1.0): 1.7.0
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: 3.6.9
 - CUDA/cuDNN version: 10.00
 - GPU models and configuration: RTX 2080
 - Any other relevant information:

**Comment by annikabrundyn** [comment]
Should this not just be added as a PL metric instead of a Bolts metric?
