### ISSUE TITLE
Add SRGAN

### ISSUE THREAD

**Issue by chris-clem** [PyTorchLightning/lightning-bolts#412]
## 🚀 Feature
How about a [SRGAN](https://arxiv.org/abs/1609.04802) implementation with PL? There are popular MIT licensed PyTorch ones out there that can serve as the basis (https://github.com/eriklindernoren/PyTorch-GAN/blob/master/implementations/srgan/srgan.py, https://github.com/https-deeplearning-ai/GANs-Public/blob/master/C3W2_SRGAN_(Optional).ipynb). 

### Motivation
SRGAN is one of the most popular image super-resolution techniques and should not be missed in the bolts library.

**Comment by akihironitta** [comment]
@chris-clem Thanks for your suggestion! I'm not familiar with super resolution, but SRGAN seems very popular as I see [the number of citations on Google Scholar](https://scholar.google.com/scholar?q=Photo-realistic+single+image+super-resolution+using+a+generative+adversarial+network), so I think it'd be great to have SRGAN.

Let's hear what other maintainers think of this suggestion :]

**Comment by aniketmaurya** [comment]
Hi @chris-clem @akihironitta 
I can take this task. Please assign it to me.
