### ISSUE TITLE
train_loss key instead of val_loss in validation_step log_dict in BYOL

### ISSUE THREAD

**Issue by souvik3333** [PyTorchLightning/lightning-bolts#496]
val_loss key is missing in validation step instead train_loss key is being used in both train and val steps.

https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/055bfff4e366b2893d03afb58f0b5545d0ae44b6/pl_bolts/models/self_supervised/byol/byol_module.py#L134

**Comment by akihironitta** [comment]
@souvik3333 Would you mind sending a PR?

**Comment by souvik3333** [comment]
sure.

**Comment by mengfeifix** [comment]
Can anybody share updates on the fix or workarounds? Thanks!

**Comment by arvindmuralie77** [comment]
Dear  @akihironitta , I think everything seems fine except for the wrong key name in the dictionary. Is there more to this issue? Otherwise, I'll send a PR.

**Comment by akihironitta** [comment]
> Is there more to this issue?

Hello @arvindmuralie77, I don't think there is. It'd be fantastic if you could send a PR.
