### ISSUE TITLE
[docs] use `versionadded`, `versionchanged` and `deprecated` directive

### ISSUE THREAD

**Issue by ydcjeff** [PyTorchLightning/lightning-bolts#544]
## 📚 Documentation
Use `.. versionadded::`, `.. versionchanged::` and `.. deprecated::` directive, so that user knows which features are added / changed / deprecated in which version and they can navigate the docs easily without changing the docs from version to version.

Ref: https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-versionadded

Similar of https://github.com/PyTorchLightning/pytorch-lightning/issues/5676

cc: @akihironitta 
What do you think?

**Comment by akihironitta** [comment]
@ydcjeff Hi, it'd be nice to have these for sure! but Bolts is still quite unstable, which means that adding these sections may lead to very noisy docs, so how about adding these sections after launching v1? (not sure when it's going be though)

**Comment by ydcjeff** [comment]
Yes, v1 is a good option.
