### ISSUE TITLE
BYOL imagenet pretrained model

### ISSUE THREAD

**Issue by yangyangkiki** [PyTorchLightning/lightning-bolts#548]
Hi 
Thanks for sharing your codes! 
may I ask where I can download a resnet50 pre-trained model on imagenet by using BYOL?
Thank you!
 
https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/99232c32602165410779c494b6bf492c2d291a71/pl_bolts/models/self_supervised/byol/byol_module.py#L34

**Comment by akihironitta** [comment]
@ananyahjha93 It's still wip and unavailable, right?
