### ISSUE TITLE
Running Diagostics for Linear Regression in Bolts

### ISSUE THREAD

**Issue by kunal-savvy** [PyTorchLightning/lightning-bolts#576]
## 🚀 Feature

Is there way to run diagnostics plots in Bolts Linear regression module?

### Motivation

Its hard to tune model without plotting residuals , ggplot or homasckedacity. Not clear how to do it here?

**Comment by annikabrundyn** [comment]
hi @kunal-savvy mind elaborating a bit? for example, what tools do you currently use in python when evaluating the fit of a linear regression model?

are you just looking for a plot of the residuals vs the fitted values?

**Comment by kunal-savvy** [comment]
No , not talking about fitted plot but diagnostics plot. Here is short link for commonality used diagnostic ( though there are more than this like multi collinirity & vif  as well. https://zhiyzuo.github.io/Linear-Regression-Diagnostic-in-Python/
