### ISSUE TITLE
importing pl_bolts makes a Jupyter xeus-python kernel crash

### ISSUE THREAD

**Issue by LucaMarconato** [PyTorchLightning/lightning-bolts#577]
## 🐛 Bug

If you run a `xeus-python` kernel in JupyterLab and then just execute `import pl_bolts`, the kernel will crash. Everything is fine with a normal `IPython` kernel. [I have also posted the bug in the `xeus-python`](https://github.com/jupyter-xeus/xeus-python/issues/422) repository since I don't know if the bug is in `pl_bolts` or in `xeus-python` (or in both).

[What is xeus-python?](https://link.medium.com/4FYop33kneb)
`xeus-python` is a replacement of `IPython` which enables valuable features in JupyterLab, like a debugger! It may became the new default choice for Jupyter users (to make a parallel, as `mamba` is replacing `conda`), so I think it is worth supporting it.

### To Reproduce

* Create a new `conda` environment. With `conda`, or `mamba`, install `xeus-python`, `jupyterlab`, `torch`, `torchvision`, `pytorch-lightning`.
* With `pip` install `pytorch-lightning-bolts`.
* Run a new JupyterLab instance with `jupyter-lab`
* Set the kernel to `XPython`
* run `import pl_bolts` in a cell
* the kernel will crash

### Expected behavior

Everything should work fine, as it happens with a standard IPython kernel.

### Environment

 - PyTorch Version (e.g., 1.0): 1.8.0
 - OS (e.g., Linux): centOS
 - How you installed PyTorch (`conda`, `pip`, source): `mamba`
 - Build command you used (if compiling from source):
 - Python version: 3.9
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration:
 - Any other relevant information:

**Comment by akihironitta** [comment]
@LucaMarconato Thank you for reporting the issue. Unfortunately, I'm not familiar with `xeus-python`, but people in the community might be able to help you debug if there's any error log or other information. One thing I'd try is to use Python {3.6,3.7,3.8} because there are still few packages that officially support 3.9, including `pytorch-lightning`.

**Comment by LucaMarconato** [comment]
The problem disappears when installing `pytorch-lightning` from conda instead than from pip, as it [has been pointed out here](https://github.com/jupyter-xeus/xeus-python/issues/422#event-4842335190). 

I close the issue as there is a workaround and probably it is not worth the effort to investigate more into it.
