### ISSUE TITLE
Can't import pytorch lightening module in colab

### ISSUE THREAD

**Issue by Dheeraj-Arremsetty** [PyTorchLightning/lightning-bolts#582]
## 🐛 Bug

Hello Pytorch Team,
I have been working on pytorch lightning for several days, I have never seen this error on Google Colab.
Not sure if there is any change that happened on colab side or lightning.

When I install pytorch lightning and try to import pytorch lightening module, it can't import and throws out the error. The same was working till yesterday. Not sure If I am doing anything wrong on my side, here is the screenshot:
![image](https://user-images.githubusercontent.com/8819938/110460357-b0d18100-8093-11eb-9c5a-87d1ca932138.png)

Same for bolts as well.
![image](https://user-images.githubusercontent.com/8819938/110462139-eaa38700-8095-11eb-9cdb-1b1628ee3664.png)

### To Reproduce

```
!pip install pytorch-lightning --quiet
import pytorch_lightning as pl
```

```
!pip install pytorch-lightning-bolts --quiet
import pl_bolts as plb
```

### Environment

 - PyTorch Version (e.g., 1.0):latest
 - OS (e.g., Linux):Colab
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by kunal-savvy** [comment]
I am also getting same error. This is blocking our work. Any help?

**Comment by akihironitta** [comment]
@Dheeraj-Arremsetty @kunal-savvy Hi, sorry for the delay. As @ajsanjoaquin mentioned, the problem should be resolved now. Mind having a look at https://github.com/PyTorchLightning/pytorch-lightning/issues/6415 or [stackoverflow](https://stackoverflow.com/questions/66538407/unable-to-import-pytorch-lightning-on-google-colab)?
