### ISSUE TITLE
Error in docs for CIFAR10DataModule

### ISSUE THREAD

**Issue by andrei-pokrovsky** [PyTorchLightning/lightning-bolts#599]
https://pytorch-lightning-bolts.readthedocs.io/en/0.2.0/api/pl_bolts.datamodules.cifar10_datamodule.html

It looks like the dm argument is passed as train_dataloader while the intention is to pass it as datamodule. This appears to be because both train_dataloader and datamodule args are optional and train_dataloader inherits from DataModule so it passes the type check.

This applies to the following code example in the documentation:

from pl_bolts.datamodules import CIFAR10DataModule

dm = CIFAR10DataModule(PATH)
model = LitModel()

Trainer().fit(model, dm) # should be datamodule=dm

**Comment by andrei-pokrovsky** [comment]
I do now see that in data_connector.py in attach_data train_dataloader is checked for whether it's an instance of LightningDataModule type but it seems counterintuitive and I would say surprising, perhaps a more self-explanatory and strict API for fit() would be better. One idea is perhaps to use a union of datamodule and a tuple of dataloaders as a second argument to fit so it's self-explanatory that they are mutually exclusive (instead of parsing out the datamodule from dataloader object).

    def attach_data(self, model, train_dataloader, val_dataloaders, datamodule):
        # if a datamodule comes in as the second arg, then fix it for the user
        if isinstance(train_dataloader, LightningDataModule):
            datamodule = train_dataloader
            train_dataloader = None

        self.__enforce_datamodule_dataloader_override(train_dataloader, val_dataloaders, datamodule)

        # set up the passed in dataloaders (if needed)
        self.attach_dataloaders(model, train_dataloader, val_dataloaders)
        self.attach_datamodule(model, datamodule, 'fit')

**Comment by akihironitta** [comment]
@andrei-pokrovsky Thank you for reporting the issue. For the docs, would you mind having a look at the latest docs? https://pytorch-lightning-bolts.readthedocs.io/en/latest/datamodules_vision.html
