### ISSUE TITLE
pypi doesn't have the latest version 0.3.1

### ISSUE THREAD

**Issue by hudeven** [PyTorchLightning/lightning-bolts#600]
## 🐛 Bug

I'm trying to use the Lightning "BoringModel" Notebook to report an issue. However, it failed due to `cannot import name 'PY3' from 'torch._six'`. This issue is fixed in https://github.com/PyTorchLightning/lightning-bolts/pull/579 and released in 0.3.1. However, pypi only has 0.3.0

### To Reproduce

Run: https://colab.research.google.com/drive/1LS4inSzLWWoBnS-v2pHe3Aq0XFp-IjEy?usp=sharing
See error: `cannot import name 'PY3' from 'torch._six'`

### Expected behavior

pip install should get the latest version 0.3.1 installed. Or the official notebook should install bolts from source if you don't plan to update pypi

**Comment by Borda** [comment]
@hudeven pls use `lightning-bolts==0.3.2rc1`

**Comment by hudeven** [comment]
@Borda it works, thanks! Is "pytorch-lightning-bolts" going to be deprecated? If so, could you update the "BoringModel" Notebook with "lightning-bolts"?

**Comment by Borda** [comment]
> If so, could you update the "BoringModel" Notebook with "lightning-bolts"?

great point, would you send a PR with this fix? :]
