### ISSUE TITLE
SimCLR loss calculation seems deviating from original paper

### ISSUE THREAD

**Issue by ricolike** [PyTorchLightning/lightning-bolts#609]
## 🐛 Bug

as title

### To Reproduce

I the denominator shall substract exp(1/temp) rather than exp(1)

#### Code sample
Suspect at here:
https://github.com/PyTorchLightning/lightning-bolts/blob/9044ed143c7f1e20164de12208f451c7a8d9718f/pl_bolts/models/self_supervised/simclr/simclr_module.py#L284

### Expected behavior

I haven't tested whether my proposed implementation would improve performance, I am suggesting any deviation from original paper be noted.

**Comment by Moadab-AI** [comment]
Actually exp(1/Temperature) should be subtracted not exp(-Temperature)

**Comment by ricolike** [comment]
> Actually exp(1/Temperature) should be subtracted not exp(-Temperature)

Exactly! I revised my comments. 
BTW, I tried the new formula on my project, which is based on Pytorch Lightning SimCLR implementation, and found no drastic difference in performance.
