### ISSUE TITLE
Does BYOL work without sync_batchnorm?

### ISSUE THREAD

**Issue by zlenyk** [PyTorchLightning/lightning-bolts#610]
Hi! I wanted to ask authors of BYOL code questions, which is more of a discussion.

I can see that you didn't use sync_batchnorm in Trainer when implementing BYOL. Per my understanding of this methods, calculating statistics over all GPUs/TPUs should be crucial for this algorithm to work well. Is this a conscious decision on your side?

I'm sorry I can't prove my hypothesis with some experimental results, but wanted to quickly check if you've considered this before running the whole training.

Thank you very much for great code!

**Comment by Borda** [comment]
@ananyahjha93 any update here?

**Comment by ananyahjha93** [comment]
We are deprecating the self-supervised learning paper implementations in bolts and instead provided a [VISSL](https://vissl.ai/) integration in PyTorch Lightning Flash which can be used to train models using self-supervised learning algorithms. You can refer to the documentation [here](https://lightning-flash.readthedocs.io/en/latest/reference/image_embedder.html).
