### ISSUE TITLE
dataset_cls() definition in VisionDataModules?

### ISSUE THREAD

**Issue by Moadab-AI** [PyTorchLightning/lightning-bolts#614]
I cant find the definition of self.dataset_cls that is being called here in VisionDataModules except for being only "typed" at the class definition:

https://github.com/PyTorchLightning/lightning-bolts/blob/9044ed143c7f1e20164de12208f451c7a8d9718f/pl_bolts/datamodules/vision_datamodule.py#L63

It doesn't seem to be inherited from superclass either. is it a bug?

**Comment by akihironitta** [comment]
@Moadab-AI Specific values for `dataset_cls` are assigned in each datamodule subclass.

https://github.com/PyTorchLightning/lightning-bolts/blob/9044ed143c7f1e20164de12208f451c7a8d9718f/pl_bolts/datamodules/mnist_datamodule.py#L43
