### ISSUE TITLE
There is an unreasonable use of MoCov2

### ISSUE THREAD

**Issue by ydar95** [PyTorchLightning/lightning-bolts#615]
In [,MoCo2_Module](https://github.com/PyTorchLightning/lightning-bolts/blob/master/pl_bolts/models/self_supervised/moco/moco2_module.py)
When PL Run this module, "validation_step" will call "forward"  to calc "output, target" , but, at "forward", it must to call "_dequeue_and_enqueue" and "_momentum_update_key_encoder"。
I think this will leak the test-set infos, and momentum-update in validation_step.

**Comment by ydar95** [comment]
![image](https://user-images.githubusercontent.com/18264807/114044453-d7185580-98b9-11eb-9444-9033eb6d8ed7.png)

**Comment by akihironitta** [comment]
@ydar95 Thank you for reporting this issue. It should be addressed in #631.
