### ISSUE TITLE
Bug with Moco on validation step

### ISSUE THREAD

**Issue by maximzubkov** [PyTorchLightning/lightning-bolts#630]
## 🐛 Bug

I was using `pytorch-ligntning` and especially `MocoV2` in the scope of my undergraduate thesis which I do at JetBrains Research, and I found the implementation of the validation stage strange. 

As was shown in the following issue https://github.com/PyTorchLightning/lightning-bolts/issues/615 , currently in `MocoV2` the `validation step` is absolutely identical  to the `train step`, and in connection with this the following two actions occur:

 - The key encoder is updated on every validation step https://github.com/PyTorchLightning/lightning-bolts/blob/5577453a6d7072724d9ae24184daf8f45d4baff7/pl_bolts/models/self_supervised/moco/moco2_module.py#L223
 - The queue is filled with both train and validation samples https://github.com/PyTorchLightning/lightning-bolts/blob/5577453a6d7072724d9ae24184daf8f45d4baff7/pl_bolts/models/self_supervised/moco/moco2_module.py#L254

Both of these events lead to the data leak, which affects both the train and validation process.

To solve this issue we can do the same thing as was done in `BYOL`, where the callback was implemented, and the update only happened at the end of the training batch https://github.com/PyTorchLightning/lightning-bolts/blob/5577453a6d7072724d9ae24184daf8f45d4baff7/pl_bolts/callbacks/byol_updates.py#L42

I can implement this feature and create a pull request with it since Moco is a very important part of my bachelor thesis. Also, I would tag @williamFalcon since he was stated in the docs as an author of this module and also @annikabrundyn who implemented `BYOL`. What do you think about it?

**Comment by akihironitta** [comment]
@maximzubkov Thank you for reporting the issue. It should be addressed in #631.
