### ISSUE TITLE
`ValueError: too many values to unpack` with simclr_module.py

### ISSUE THREAD

**Issue by ethanwharris** [PyTorchLightning/lightning-bolts#640]
## 🐛 Bug

Bug report from slack: Getting a ValueError with simclr

### To Reproduce

https://colab.research.google.com/drive/18G-7vnx9LyaADoZZTq_Wh5nKS_exwOHU?usp=sharing

**Comment by ethanwharris** [comment]
Related simclr issue here: https://github.com/PyTorchLightning/pytorch-lightning/issues/7488

**Comment by ta-ja** [comment]
Hello, I ran into the same problem today and figured out the cause. It is important to actually call `SimCLRTrainDataTransform.transform` method from the `__getitem__` method inside the used dataset. The [method](https://github.com/PyTorchLightning/lightning-bolts/blob/ad771c615284816ecadad11f3172459afdef28e3/pl_bolts/models/self_supervised/simclr/transforms.py#L85) will return the correct tuple with 3 items.

I believe this issue can be closed.
