### ISSUE TITLE
I think this line is redundant?

### ISSUE THREAD

**Issue by RyannDaGreat** [PyTorchLightning/lightning-bolts#643]
This is a tiny issue so I'm not sure it's worth making a pull request for. That being said, I don't understand the purpose of the 3rd line here:

```
if not isinstance(states, list):
    states = [states]
if not isinstance(states, torch.Tensor):
    states = torch.tensor(states, device=device)
```

We could add the following assertions...

```
if not isinstance(states, list):
    states = [states]
assert isinstance(states,list)
assert not isinstance(states, torch.Tensor)
if not isinstance(states, torch.Tensor):
    states = torch.tensor(states, device=device)
```

And then get rid of the conditional...

```
if not isinstance(states, list):
    states = [states]
states = torch.tensor(states, device=device)
```

https://github.com/PyTorchLightning/lightning-bolts/blob/cb687e6cd04652fbf028d3f788d1b422138f6be6/pl_bolts/models/rl/common/agents.py#L130

**Comment by akihironitta** [comment]
@RyannDaGreat Thank you for reporting this issue. Would you be interested in sending a PR?

**Comment by RyannDaGreat** [comment]
Yes, I'll send one!
