### ISSUE TITLE
SWAV result on STL10 no longer valid

### ISSUE THREAD

**Issue by JACKHAHA363** [PyTorchLightning/lightning-bolts#656]
## 🐛 Bug

I am trying to reproduce the STL10 result as is suggested [here](https://pytorch-lightning-bolts.readthedocs.io/en/latest/self_supervised_models.html#stl-10-baseline). I clone the latest the repo and try to run
```
python swav_module.py
    --online_ft
    --gpus 1
    --lars_wrapper
    --batch_size 128
    --learning_rate 1e-3
    --gaussian_blur
    --queue_length 0
    --jitter_strength 1.
    --nmb_prototypes 512
```
Since `--lars_wrapper` is no longer available, I use `--optimizer lars`. I also disable the `fast_dev_run`. However, at 50 epochs, the val acc is around 20%, unlike the 70% in the webpage.

### Environment

 - PyTorch: 1.7.1
 - OS: ubuntu
 - How you installed PyTorch: (`pip`)
 - Python version: 3.8
 - CUDA/cuDNN version: cuda11.0

**Comment by Borda** [comment]
@ananyahjha93 any update here?

**Comment by ananyahjha93** [comment]
We are deprecating the self-supervised learning paper implementations in bolts and instead provided a [VISSL](https://vissl.ai/) integration in PyTorch Lightning Flash which can be used to train models using self-supervised learning algorithms. You can refer to the documentation [here](https://lightning-flash.readthedocs.io/en/latest/reference/image_embedder.html).
