### ISSUE TITLE
SimCLR cifar-10 pretrained model url is not correct

### ISSUE THREAD

**Issue by MiladInk** [PyTorchLightning/lightning-bolts#658]
Hi All! Thanks for creating the awesome lightning-bolts!
I just needed pre-trained SimCLR on cifar-10 from [here ](https://pytorch-lightning-bolts.readthedocs.io/en/latest/self_supervised_models.html#simclr) and it seems actually the url provided in the documentations is for imagenet. 
![image](https://user-images.githubusercontent.com/18356953/120592872-8d0ca580-c40c-11eb-9a5b-4b1a7ec19920.png)

**Comment by ananyahjha93** [comment]
Thanks for bringing this to our notice, I will send in a PR.

**Comment by m-kuoch** [comment]
Does anyone have the correct URL readily available.  I'm also interested in using the pretrained CIFAR-10 model.  Thanks!

**Comment by ananyahjha93** [comment]
done, sorry @m-kuoch this completely slipped from my list of TODOs.

**Comment by m-kuoch** [comment]
@ananyahjha93 No problem, thanks for the fast reply!
