### ISSUE TITLE
Add ability add custom/modified backbone to FasterRCNN

### ISSUE THREAD

**Issue by abhayraw1** [PyTorchLightning/lightning-bolts#660]
## 🚀 Feature
In the [Faster RCNN](https://github.com/PyTorchLightning/lightning-bolts/blob/master/pl_bolts/models/detection/faster_rcnn/faster_rcnn_module.py) bolt, it would be awesome to have the functionality to pass custom `pl.LightningModules` or `torch.nn.Module` backbone. In the current state, the constructor requires the `backbone` argument to be a `str`

https://github.com/PyTorchLightning/lightning-bolts/blob/c3b60de7dc30c5f7947256479d9be3a042b8c182/pl_bolts/models/detection/faster_rcnn/faster_rcnn_module.py#L33-L63

### Motivation

I wanted to try some custom version of the ResNet model in the Faster RCNN pipeline and thought this functionality might help.

### Alternatives

These are the two workarounds that I think would work:
1. Reassign the backbone manually. Similar to how we reassign the predictor head in torchvision tutorials - [link](https://pytorch.org/tutorials/intermediate/torchvision_tutorial.html#an-instance-segmentation-model-for-pennfudan-dataset). 
2. Subclass the `FasterRCNN` and manually reassign the backbone

**Comment by Borda** [comment]
@abhayraw1 that would be great, do you want to implement it?

**Comment by abhayraw1** [comment]
@Borda sure! Will drop a PR soon!
