### ISSUE TITLE
bolts.MNISTDataModule.prepare_data() tries to get the data from incorrect URL

### ISSUE THREAD

**Issue by murphyk** [PyTorchLightning/lightning-bolts#670]
bolts.MNISTDataModule.prepare_data() tries to get the data from incorrect URL.
It says
` Downloading http://yann.lecun.com/exdb/mnist/https://ossci-datasets.s3.amazonaws.com/mnist/train-images-idx3-ubyte.gz.`
 Here is the code to reproduce the issue:
```
from pl_bolts.datamodules import MNISTDataModule
dm = MNISTDataModule(num_workers=0, data_dir='data')
dm.prepare_data() # force download - fails!
```

**Comment by Borda** [comment]
@ananthsub @murphyk moved to Bolts as it :rabbit:

**Comment by Borda** [comment]
We are using upstream TorchVision datasets, so if there is an issue with download past, pls open an issue on the TV side...
see https://github.com/PyTorchLightning/lightning-bolts/blob/9990749f53ee5992dc89ff106a24e609300dca40/pl_bolts/datamodules/mnist_datamodule.py#L42
