### ISSUE TITLE
Make EMNISTDataModule

### ISSUE THREAD

**Issue by murphyk** [PyTorchLightning/lightning-bolts#672]
(Moved from https://github.com/PyTorchLightning/pytorch-lightning/issues/8110.)

It would be useful to have a DM for https://www.tensorflow.org/datasets/catalog/emnist.

### Motivation

EMNIST is a much better dataset than MNIST, since it has more classes (0-9, a-z, A-Z), more data (4x), and more inherent ambiguity, yet it still easy to deal with computationally.

![image](https://user-images.githubusercontent.com/4632336/123210742-4d6b3380-d477-11eb-80da-3e9a74a18a07.png)

**Comment by akihironitta** [comment]
@murphyk Reopening this issue as I believe this would be a great addition to Bolts!
