### ISSUE TITLE
PyTorch Lightning Resnet returns a list, instead of a tensor.

### ISSUE THREAD

**Issue by souravraha** [PyTorchLightning/lightning-bolts#675]
https://github.com/PyTorchLightning/lightning-bolts/blob/48e75217d8c10e5726eafca2c85e795a993477e7/pl_bolts/models/self_supervised/resnets.py#L277

The code for Resnet class in Lightning Bolts needs modification. I found a discrepancy in the line referenced here.

1. The self.fc layer (final linear layer) needs to be implemented.
2. Please remove the square brackets from the next line. The output should be a tensor, not a list.

**Comment by edenlightning** [comment]
Thanks for the issue! Any chance you want to try and submit a fix?

**Comment by souravraha** [comment]
Sure. I shall do this within this weekend.

**Comment by souravraha** [comment]
False alarm, it seems that this code is intended to extract features from different layers of the ResNet. I had assumed that this code ought to give the final output from the ResNet. The original code is correct for its intended purpose.
