### ISSUE TITLE
Small bug in nt_xent_loss for SimCLR model

### ISSUE THREAD

**Issue by z-fabian** [PyTorchLightning/lightning-bolts#681]
## 🐛 Bug

Adding `eps` is done twice, second is unnecessary in `nt_xent_loss`: first [here](https://github.com/PyTorchLightning/lightning-bolts/blob/0045e649f9bdbe3195530c57bdbe9daa399a9710/pl_bolts/models/self_supervised/simclr/simclr_module.py#L253) and then again [here](https://github.com/PyTorchLightning/lightning-bolts/blob/0045e649f9bdbe3195530c57bdbe9daa399a9710/pl_bolts/models/self_supervised/simclr/simclr_module.py#L259).

We should change
```
 loss = -torch.log(pos / (neg + eps)).mean()
```
to
```
 loss = -torch.log(pos / neg).mean()
```

**Comment by ananyahjha93** [comment]
We are deprecating the self-supervised learning paper implementations in bolts and instead provided a [VISSL](https://vissl.ai/) integration in PyTorch Lightning Flash which can be used to train models using self-supervised learning algorithms. You can refer to the documentation [here](https://lightning-flash.readthedocs.io/en/latest/reference/image_embedder.html).
