### ISSUE TITLE
Iterator error after pip install

### ISSUE THREAD

**Issue by mariakesa** [PyTorchLightning/lightning-bolts#682]
Hello,

Thanks so much for an awesome package!:-)

I recently re-pip installed plbolts on a google colab notebook. My code worked before. I'm trying to train a DQN.

On importing the DQN (from pl_bolts.models.rl import DQN), I get the following error:
```
/usr/local/lib/python3.7/dist-packages/torch/utils/data/_typing.py in _dp_init_subclass(sub_cls, *args, **kwargs)
    369                      return_hint.__origin__ == collections.abc.Iterator)):
    370                 raise TypeError("Expected 'Iterator' as the return annotation for `__iter__` of {}"
--> 371                                 ", but found {}".format(sub_cls.__name__, _type_repr(hints['return'])))
    372             data_type = return_hint.__args__[0]
    373             if not issubtype(data_type, sub_cls.type.param):

TypeError: Expected 'Iterator' as the return annotation for `__iter__` of ExperienceSourceDataset, but found typing.Iterable
```
Help would be appreciated!

Thank you:-)

**Comment by Borda** [comment]
hi, can you tell us how to reproduce, what code have you run?

**Comment by mariakesa** [comment]
Hey,

Thanks for the quick reply!

I ran:

!pip install atari-py
!pip install pytorch-lightning-bolts
!pip install pytorch-lightning

from pl_bolts.models.rl import DQN
import time
from pytorch_lightning import Trainer

start=time.time()
#dqn = DQN("DemonAttack-v0")
trainer = Trainer(gpus=1)
trainer.fit(dqn)
end=time.time()
print(end-start)

The code failed on the DQN import.

**Comment by gurlina** [comment]
I encountered the same error while trying to simply import the `pl_bolts` library after successful installation. This was executed within the CoLab environment, and the same code used to work a couple of weeks ago.

```
!pip install pytorch-lightning
!pip install pytorch-lightning-bolts

import pytorch_lightning as pl
import pl_bolts

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-17-49491e23d5a9> in <module>()
      1 import pytorch_lightning as pl
----> 2 import pl_bolts
      3 
      4 print(f"pl version: {pl.__version__}")
      5 print(f"pl_bolts version: {pl_bolts.__version__}")

5 frames
/usr/local/lib/python3.7/dist-packages/torch/utils/data/_typing.py in _dp_init_subclass(sub_cls, *args, **kwargs)
    369                      return_hint.__origin__ == collections.abc.Iterator)):
    370                 raise TypeError("Expected 'Iterator' as the return annotation for `__iter__` of {}"
--> 371                                 ", but found {}".format(sub_cls.__name__, _type_repr(hints['return'])))
    372             data_type = return_hint.__args__[0]
    373             if not issubtype(data_type, sub_cls.type.param):

TypeError: Expected 'Iterator' as the return annotation for `__iter__` of ExperienceSourceDataset, but found typing.Iterable
```

**Comment by mariakesa** [comment]
Yep, I was also working in Colab. The funny thing is that some time before the code worked.

**Comment by gurlina** [comment]
I found that installing the latest version from the Master branch fixes the import problem (no guarantees, though, that it wouldn't break something else...):

`pip install git+https://github.com/PytorchLightning/lightning-bolts.git@master --upgrade`
