### ISSUE TITLE
Add all datamodules to documentation using sphinx docs-auto-generation

### ISSUE THREAD

**Issue by sugatoray** [PyTorchLightning/lightning-bolts#685]
## 📚 Documentation

At present most of the following datamodules are available under Vision Datamodule in the documentation. However, this is not visible to the user from the sidebar. Neither it is available from the Datmodule documentation, as links directing to each of the Datamodules below.

In other words, there should be at least a single point of entry (perhaps in Datamodule in the docs) where the user should be able to find links to all the datamodules directly.

  - [x] `BinaryMNISTDataModule` 
  - [x] `CIFAR10DataModule` 
  - [x] `CityscapesDataModule` 
  - [x] `FashionMNISTDataModule` 
  - [x] `ImagenetDataModule` 
  - [x] `KittiDataModule` 
  - [x] `MNISTDataModule` 
  - [x] `SSLImagenetDataModule` 
  - [x] `STL10DataModule` 

[EDIT]: *The original description of this issue has been updated.*

![image](https://user-images.githubusercontent.com/10201242/124799131-d6737780-df19-11eb-98e9-a29c73b896b6.png)

## What could be helpful?

Here is an example from [`torchvision.models`](https://pytorch.org/vision/stable/models.html). A list of models available like this makes it easier for the user to navigate to the relevant docs page. Similarly, a list of datamodules (perhaps in `datamodules.rst`) pointing to their respective documentation (be it in Vision Datamodules or Sklearn Datamodules), will be very helpful.

![image](https://user-images.githubusercontent.com/10201242/124799924-b0020c00-df1a-11eb-9daf-63773cdb6668.png)

**Comment by akihironitta** [comment]
@sugatoray Could you elaborate on why we need this? We already have [the docs for datamodules here](https://lightning-bolts.readthedocs.io/en/latest/datamodules_vision.html).

**Comment by sugatoray** [comment]
> @sugatoray Could you elaborate on why we need this? We already have [the docs for datamodules here](https://lightning-bolts.readthedocs.io/en/latest/datamodules_vision.html).

@akihironitta Thank you for pointing me to the docs for Vision Module. However, after looking at it I changed the issue description. It will be nice to be able to see all the datamodules easily accessible from a single point of entry: either from the sidebar or from here: https://lightning-bolts.readthedocs.io/en/latest/, or (preferably) both. Please see the updated issue description.

**Comment by sugatoray** [comment]
This issue should be closed as it was taken care of already.
