### ISSUE TITLE
SimCLR pre-training code in the tutorial not working

### ISSUE THREAD

**Issue by gitHub882000** [PyTorchLightning/lightning-bolts#689]
## ❓ Questions and Help

I encountered 2 errors when running the example code for pre-training SimCLR [here](https://pytorch-lightning-bolts.readthedocs.io/en/latest/self_supervised_models.html#simclr) on Google Colab.

### 1: SimCLR missing 'gpus' argument

When I tried the example code in the tutorial. I got the following error: 

```
TypeError                                 Traceback (most recent call last)
<ipython-input-2-883f9da303ec> in <module>()
     11 
     12 # model
---> 13 model = SimCLR(num_samples=dm.num_samples, batch_size=dm.batch_size, dataset='cifar10')
     14 
     15 # fit

TypeError: __init__() missing 1 required positional argument: 'gpus'
```

In this first problem, I want to know what the meaning of this parameter is when I can specify the number of GPUs used in the ```Trainer```? For example: ```trainer = pl.Trainer(gpus=1)```. And also how do I configure this 'gpus' parameter of SimCLR model when I want to use TPU with this ```trainer = pl.Trainer(tpu_cores=8)``` instead? 

### 2: Trainer.fit() can't set attribute

Due to the first error, I modify the code to be:

```py
import pytorch_lightning as pl
from pl_bolts.models.self_supervised import SimCLR
from pl_bolts.datamodules import CIFAR10DataModule
from pl_bolts.models.self_supervised.simclr.transforms import (
    SimCLREvalDataTransform, SimCLRTrainDataTransform)


dm = CIFAR10DataModule(num_workers=0)
dm.train_transforms = SimCLRTrainDataTransform(32)
dm.val_transforms = SimCLREvalDataTransform(32)


# Modify here
model = SimCLR(gpus = 0, num_samples=dm.num_samples, batch_size=dm.batch_size, dataset='cifar10') # I want to use tpu instead

# And here
trainer = pl.Trainer(tpu_cores=8)
trainer.fit(model, datamodule=dm)
```

Now I get another error:

```
AttributeError                            Traceback (most recent call last)
<ipython-input-10-655a4e133f69> in <module>()
     19 # fit
     20 trainer = pl.Trainer(tpu_cores=8)
---> 21 trainer.fit(model, datamodule=dm)

4 frames
/usr/local/lib/python3.7/dist-packages/pytorch_lightning/accelerators/accelerator.py in _move_optimizer_state(self)
    118             for p, v in opt.state.items():
    119                 state[p] = apply_to_collection(v, torch.Tensor, move_data_to_device, self.root_device)
--> 120             opt.state = state
    121 
    122     def dispatch(self, trainer: 'pl.Trainer') -> None:

AttributeError: can't set attribute
```

### My system information is:
```
- OS: Linux
- Packages: 
         Pytorch (1.8.0+cu111)
         Pytorch-Lightning (1.3.8)
         Pytorch-Lightning Bolts (0.3.2)
         Torch XLA (1.8)
- Resource:
         GPU available: False, used: False
         TPU available: True, using: 8 TPU cores
```

Any help is really appreciated.

**Comment by ananyahjha93** [comment]
We are deprecating the self-supervised learning paper implementations in bolts and instead provided a [VISSL](https://vissl.ai/) integration in PyTorch Lightning Flash which can be used to train models using self-supervised learning algorithms. You can refer to the documentation [here](https://lightning-flash.readthedocs.io/en/latest/reference/image_embedder.html).
