### ISSUE TITLE
Issue with importing pl_bolts

### ISSUE THREAD

**Issue by bgswaroop** [PyTorchLightning/lightning-bolts#707]
## 🐛 Bug

Importing `pl_bolts` raises the following error:
> TypeError: Expected 'Iterator' as the return annotation for `__iter__` of ExperienceSourceDataset, but found typing.Iterable

### To Reproduce

1. Install `pytorch-lightning-bolts` from pip
2. Add the `import pl_bolts` statement to a python script
3. Execute it
  

#### Code sample

    import pl_bolts

### Expected behavior

The program to import the specified module without errors.

### Error Messages

	/<...>/python_venv/pl_bolts/lib/python3.9/site-packages/setuptools/distutils_patch.py:25: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
	  warnings.warn(
	Traceback (most recent call last):
	  File "/<...>/test_pl_bolts.py", line 1, in <module>
		import pl_bolts
	  File "/<...>/python_venv/pl_bolts/lib/python3.9/site-packages/pl_bolts/__init__.py", line 19, in <module>
		from pl_bolts import (  # noqa: E402
	  File "/<...>/python_venv/pl_bolts/lib/python3.9/site-packages/pl_bolts/datamodules/__init__.py", line 5, in <module>
		from pl_bolts.datamodules.experience_source import DiscountedExperienceSource, ExperienceSource, ExperienceSourceDataset
	  File "/<...>/python_venv/pl_bolts/lib/python3.9/site-packages/pl_bolts/datamodules/experience_source.py", line 24, in <module>
		class ExperienceSourceDataset(IterableDataset):
	  File "/<...>/python_venv/pl_bolts/lib/python3.9/site-packages/torch/utils/data/_typing.py", line 273, in __new__
		return super().__new__(cls, name, bases, namespace, **kwargs)  # type: ignore[call-overload]
	  File "/<...>/python_venv/Python3.9/lib/python3.9/abc.py", line 85, in __new__
		cls = super().__new__(mcls, name, bases, namespace, **kwargs)
	  File "/<...>/python_venv/pl_bolts/lib/python3.9/site-packages/torch/utils/data/_typing.py", line 370, in _dp_init_subclass
		raise TypeError("Expected 'Iterator' as the return annotation for `__iter__` of {}"
	TypeError: Expected 'Iterator' as the return annotation for `__iter__` of ExperienceSourceDataset, but found typing.Iterable

### Environment

 - PyTorch Version (e.g., 1.0): 1.9.0
 - pytorch-lightning-bolts Version : 0.3.2
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.9.0
 - CUDA/cuDNN version: 10.1.243
 - GPU models and configuration: 2 GPUs - NVIDIA GTX 1080 Ti installed on a single node.  
 - Any other relevant information:

### Additional context

None.

**Comment by Borda** [comment]
> * Install `pytorch-lightning-bolts` from pip
> * Add the `import pl_bolts` statement to a python script
> * Execute it

seems you are using a deprecated version https://pypi.org/project/lightning-bolts

**Comment by bgswaroop** [comment]
@Borda Thanks for pointing it out. As per your suggestion, after installing `pip install lightning-bolts`, I do not get any error. I noticed that there are two versions for bolts:
- [https://pypi.org/project/lightning-bolts](https://pypi.org/project/lightning-bolts)
- [https://pypi.org/project/pytorch-lightning-bolts](https://pypi.org/project/pytorch-lightning-bolts)  - deprecated?

Just to clarify, the second version is deprecated, right?

**Comment by Borda** [comment]
> Just to clarify, the second version is deprecated, right?

Correct =)
