### ISSUE TITLE
Future state of lightning-bolts!

### ISSUE THREAD

**Issue by SeanNaren** [PyTorchLightning/lightning-bolts#712]
## 🚀 Feature

After discussion with the Lightning team and the piling up issues I think it's important to address the library and some of its pain points. Overall the goal is to improve the libraries functionality whilst honing exactly what this library will deliver!

### Motivation

The Lightning team doesn't have time to assist with issues/PRs around specific research pieces. This primarily is the SSL implementations/pieces. This leads to a lot of smelly code, and horrible import errors as we've seen so far.

#### Focus on general applied research components; callbacks, datamodules, datasets

Move away from specific model implementations and writing applied research. As we've seen these deprecate very quickly, and probably require a standalone repository to ensure support.

#### Deprecate SSL implementations, encourage Lightning Flash VISSL

Since we'll not be able to support the SSL implementations in bolts, I suggest we make it clear that any issues around these may be stale. We'll continue to encourage contributions to fix any issues with them for users who still use them, but strongly recommend looking at Lightning Flash VISSL integration (once integrated https://github.com/PyTorchLightning/lightning-flash/pull/682).

#### Re-write README/documentation to be component focused, deprecate/drop model specific implementations

Should be fairly explanatory. Try to hone in and make clear what the library is about. 

### Additional context

We'll be introducing more third-party callbacks, and introducing more components to help research :) Before doing this, we want to clear up the repository to support this!

cc @Borda @akihironitta @tchaton

**Comment by akihironitta** [comment]
@SeanNaren Thank you for bringing up this issue! I agree with you on all the points listed there.
