### ISSUE TITLE
No module named 'pl_bolts.models.autoencoders'

### ISSUE THREAD

**Issue by yjkweon24** [PyTorchLightning/lightning-bolts#754]
As what "https://github.com/PyTorchLightning/lightning-bolts/issues/707" said, I removed pytorch lightning bolts module, and I successfully installed lightning bolts, but I kept getting an error below:

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_3033447/2816402708.py in <module>
      2 from torch import nn
      3 import torch
----> 4 from pl_bolts.models.autoencoders.components import (
      5     resnet18_decoder,
      6     resnet18_encoder,

ModuleNotFoundError: No module named 'pl_bolts.models.autoencoders'
```

I am running it on ipynb
Torch 1.9.1
lightning-bolts 0.4.0
How you installed PyTorch (conda, pip, source): pip
Build command you used (if compiling from source):
Python version: 3.8.2

**Comment by Programmer-RD-AI** [comment]
I tried this localy but it works.

Env
- Torch - 1.9.1
- PyTorch Lightning - 1.4.9
- Lightning Bolts - 0.4.0
- Python - 3.8.8
- Env(pip,conda) - Conda

**Comment by yjkweon24** [comment]
Thanks for getting back to me. But I faced the similar issues below:

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_4044614/4231511349.py in <module>
      1 from torch import nn
      2 import torch
----> 3 from pl_bolts.callbacks.ssl_online import SSLOnlineEvaluator
      4 from pl_bolts.models.autoencoders.components import (
      5     resnet18_decoder,

ModuleNotFoundError: No module named 'pl_bolts.callbacks.ssl_online'

PyTorch Lightning - 1.4.9
Lightning Bolts - 0.4.0
torch  -  1.10.0+cu113

**Comment by Programmer-RD-AI** [comment]
[requirements.txt](https://github.com/PyTorchLightning/lightning-bolts/files/7461038/requirements.txt)

**Comment by Programmer-RD-AI** [comment]
These are the dependencies I used

**Comment by Programmer-RD-AI** [comment]
Can you try downgrading from 1.4.9

**Comment by yjkweon24** [comment]
Thanks for sharing the env lists.
Yeah I downgraded to 1.3.8 but still faced the same issue. By the way I am using the jupyter lab on the server.

**Comment by Programmer-RD-AI** [comment]
hi,
Is it different in VSCode and other.

**Comment by yjkweon24** [comment]
Oh no, I found a problem here.
I upgraded python version to 3.8.8 and now it is working fine. 
3.8.2 keeps facing error. Not sure why though...
