### ISSUE TITLE
prepare_data in imagenet_datamodule ignores the meta_dir argument and requires meta.bin to be in the train and val folders

### ISSUE THREAD

**Issue by Neabfi** [PyTorchLightning/lightning-bolts#769]
## 🐛 Bug

_imagenet_datamodule_ has a _meta_dir_ parameter to specify the path to the _meta.bin_ file. However _prepare_data_ requires the _meta.bin_ file to be in the train and the val folder.

https://github.com/PyTorchLightning/lightning-bolts/blob/8b4d90d7443ac263fd246e2745c267439f4b9274/pl_bolts/datamodules/imagenet_datamodule.py#L116-L144

### Expected behavior

I would expect _prepare_data_ to use _self.meta_dir_ to locate the _meta.bin_ file. 

### Environment

PyTorch Version: 1.7.1
OS: CentOS Linux
How you installed PyTorch: conda
Python version: 3.8.10
CUDA/cuDNN version: 10.1
GPU models and configuration: m40

**Comment by bsridatta** [comment]
Yup, either the meta_dir parameter should be removed or the code should read from the meta_dir path. I would be happy to contribute to this. Please let me know if the user should be able to specify meta_dir. Thanks!
