### ISSUE TITLE
SSL online evaluator

### ISSUE THREAD

**Issue by kfarivar** [PyTorchLightning/lightning-bolts#772]
https://github.com/PyTorchLightning/lightning-bolts/blob/533c09be97754f7c951ea29a432ca105223fd1bd/pl_bolts/callbacks/ssl_online.py#L109
I think it makes more sense to zero the grad first then take the gradient step. Is there a reason for doing this in reverse ?

**Comment by ananyahjha93** [comment]
We are deprecating the self-supervised learning paper implementations in bolts and instead provided a [VISSL](https://vissl.ai/) integration in PyTorch Lightning Flash which can be used to train models using self-supervised learning algorithms. You can refer to the documentation [here](https://lightning-flash.readthedocs.io/en/latest/reference/image_embedder.html).
