### ISSUE TITLE
Clarification of Self-Supervised Models' Pretraining

### ISSUE THREAD

**Issue by RylanSchaeffer** [PyTorchLightning/lightning-bolts#778]
I'm finding that many of the self-supervised models have ambiguous statements on how they were pretrained.  For instance, SimCLR's documentation suggests that it was pretrained on CIFAR-10, but the model path suggests it was pretrained on imagenet (which makes more sense):

![image](https://user-images.githubusercontent.com/8942987/144128697-1df14722-81cb-40e4-98c9-e3bd19d76934.png)

Could someone please clarify in the documentation how each model was pretrained?

Thanks in advance!

**Comment by ananyahjha93** [comment]
We are deprecating the self-supervised learning paper implementations in bolts and instead provided a [VISSL](https://vissl.ai/) integration in PyTorch Lightning Flash which can be used to train models using self-supervised learning algorithms. You can refer to the documentation [here](https://lightning-flash.readthedocs.io/en/latest/reference/image_embedder.html).
