### ISSUE TITLE
Clarification of SwAV's forward method

### ISSUE THREAD

**Issue by RylanSchaeffer** [PyTorchLightning/lightning-bolts#782]
I noticed that SwAV's forward method only calls the model (resnet18 or resnet50)'s `forward_backbone` method but not the model's `forward` method:

```
    def forward(self, x):
        # pass single batch from the resnet backbone
        return self.model.forward_backbone(x)
```

Why is this? I can't find an explanation of this in the documentation or the paper.

**Comment by ananyahjha93** [comment]
@RylanSchaeffer the forward function of the lightning module is designed for validation and inference times, where we just want the features from the encoder.

Also,

We are deprecating the self-supervised learning paper implementations in bolts and instead provided a [VISSL](https://vissl.ai/) integration in PyTorch Lightning Flash which can be used to train models using self-supervised learning algorithms. You can refer to the documentation [here](https://lightning-flash.readthedocs.io/en/latest/reference/image_embedder.html).
