### ISSUE TITLE
Logging and progress bar values not detaching

### ISSUE THREAD

**Issue by loodvn** [PyTorchLightning/lightning-bolts#793]
## 🐛 Bug

Possibly related to #405 .

In several bolts models (such as LogisticRegression) https://github.com/PyTorchLightning/Lightning-Bolts/blob/master/pl_bolts/models/regression/logistic_regression.py#L13-L116, the logged losses aren't being detached.

I get the following error (which is the same error as in a [PL GAN tutorial](https://pytorch-lightning.readthedocs.io/en/stable/notebooks/lightning_examples/basic-gan.html)):

```
.../pytorch_lightning/trainer/connectors/logger_connector/result.py:405: LightningDeprecationWarning: One of the returned values {'progress_bar', 'log'} has a `grad_fn`. We will detach it automatically but this behaviour will change in v1.6. Please detach it manually: `return {'loss': ..., 'something': something.detach()}`
```

#### Code sample

```python
from sklearn.datasets import load_iris
from pl_bolts.models.regression import LogisticRegression
from pl_bolts.datamodules import SklearnDataModule
import pytorch_lightning as pl
from pytorch_lightning.loggers import WandbLogger

wandb_logger = WandbLogger(
    log_model=False,
)

# use any numpy or sklearn dataset
X, y = load_iris(return_X_y=True)
dm = SklearnDataModule(X, y)

# build model
model = LogisticRegression(input_dim=4, num_classes=3)

# fit
trainer = pl.Trainer(max_epochs=5, logger=wandb_logger, log_every_n_steps=1)  # For some reason using Tensorboard logger doesn't trigger the warning?
trainer.fit(model, train_dataloaders=dm.train_dataloader(), val_dataloaders=dm.val_dataloader())
```

### Expected behavior

No error. 
I think the error comes from e.g. line 72: https://github.com/PyTorchLightning/Lightning-Bolts/blob/master/pl_bolts/models/regression/logistic_regression.py#L72 
```python
tensorboard_logs = {"train_ce_loss": loss}
progress_bar_metrics = tensorboard_logs
return {"loss": loss, "log": tensorboard_logs, "progress_bar": progress_bar_metrics}
```

where `tensorboard_logs` should be 
```python
tensorboard_logs = {"train_ce_loss": loss.detach()}  # Or .detach().cpu()?
```

### Environment

- PyTorch Version (e.g., 1.0): 1.7.1
- OS (e.g., Linux): Linux
- How you installed PyTorch (`conda`, `pip`, source): `conda`
- Build command you used (if compiling from source):
- Python version: 3.7
- CUDA/cuDNN version:
- GPU models and configuration:
- Any other relevant information: PyTorch Lightning 1.5.8; Lightning Bolts v0.5.0

### Additional context

As an aside, for some reason in 1.5.8 a few warnings don't get triggered with default (Tensorboard) logging, only when I use another logger like Wandb. Found it interesting.

**Comment by loodvn** [comment]
And since 1.6 (as the deprecation warning says, but specifically https://github.com/PyTorchLightning/pytorch-lightning/pull/10424) this may cause memory leaks from not detaching

**Comment by Borda** [comment]
Hi @loodvn are you interested in sending out fix? :]

**Comment by loodvn** [comment]
Unfortunately not, sorry - I gave #794 a go locally over the weekend, but the next two weeks (at least) I am moving country so not available for some time 😞
