### ISSUE TITLE
pypi: Explicitly mention that `pytorch-lightning-bolts` is old, `lightning-bolts` is new?

### ISSUE THREAD

**Issue by EricCousineau-TRI** [PyTorchLightning/lightning-bolts#795]
## 🐛 Bug

The most up-to-date PyPI package appears to be https://pypi.org/project/lightning-bolts/#history
However, there is also this package: https://pypi.org/project/pytorch-lightning-bolts/#history

This was mentioned at https://github.com/PyTorchLightning/lightning-bolts/issues/600#issuecomment-803186775

### To Reproduce

See above.

#### Code sample

N/A

### Expected behavior

It is obvious from PyPI page which is the most obvious.

### Environment

N/A

### Additional context

N/A

**Comment by EricCousineau-TRI** [comment]
Perhaps it's possible for whomeever has PyPI permissions to update this overview (and perhaps remove the "Latest Version" badge, if possible?)

> ![image](https://user-images.githubusercontent.com/26719449/148703502-486e6f73-5762-4192-8543-2d6998dc9b69.png)

**Comment by Borda** [comment]
you are right that https://pypi.org/project/pytorch-lightning-bolts is deprecated

**Comment by Borda** [comment]
![image](https://user-images.githubusercontent.com/6035284/148927011-22b8150d-c719-4751-bf14-6518ca57b3d0.png)

**Comment by EricCousineau-TRI** [comment]
Excellent, thank you so much!
